/* Automatically generated by './build/bin/build-business-entry.js' */

import BizCard from './biz-card/index.js';
import BizDisplay from './biz-display/index.js';

const components = [
  BizCard,
  BizDisplay
];

const install = function(Vue) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '2.15.16',
  install,
  BizCard,
  BizDisplay
};
