'use strict';

const fs = require('fs');
const http = require('http');
const path = require('path');
const { URL } = require('url');

let sass;

try {
  sass = require('node-sass');
} catch (error) {
  sass = null;
}

const ROOT_DIR = path.resolve(__dirname, '..');
const THEME_SRC_DIR = path.join(ROOT_DIR, 'packages', 'theme-chalk', 'src');
const THEME_ENTRY_FILE = path.join(THEME_SRC_DIR, 'index.scss');
const COMMON_VAR_FILE = path.join(THEME_SRC_DIR, 'common', 'var.scss');
const PORT = Number(process.env.PORT || process.env.THEME_API_PORT || 3008);

const themeStore = Object.create(null);
const defaultGlobalTheme = extractDefaultTheme(COMMON_VAR_FILE);

function isPlainObject(value) {
  return Object.prototype.toString.call(value) === '[object Object]';
}

function clone(value) {
  if (value == null) {
    return value;
  }

  return JSON.parse(JSON.stringify(value));
}

function normalizeThemeConfig(input) {
  const theme = isPlainObject(input) ? clone(input) : {};
  const global = isPlainObject(theme.global) ? theme.global : {};
  const local = isPlainObject(theme.local) ? theme.local : {};

  theme.global = global;
  theme.local = local;

  return theme;
}

function normalizeVarName(rawName) {
  if (typeof rawName !== 'string') {
    return null;
  }

  const name = rawName.trim();
  if (!name) {
    return null;
  }

  if (/^\$--[A-Za-z0-9_-]+$/.test(name) || /^\$[A-Za-z0-9_-]+$/.test(name)) {
    return name;
  }

  if (/^--[A-Za-z0-9_-]+$/.test(name)) {
    return `$${name}`;
  }

  if (/^[A-Za-z0-9_-]+$/.test(name)) {
    return `$--${name.replace(/_/g, '-')}`;
  }

  return null;
}

function normalizeVarValue(rawValue) {
  if (rawValue == null) {
    return null;
  }

  if (typeof rawValue === 'number') {
    return String(rawValue);
  }

  if (typeof rawValue === 'boolean') {
    return rawValue ? 'true' : 'false';
  }

  return String(rawValue).trim();
}

function collectVariables(section) {
  if (!isPlainObject(section)) {
    return [];
  }

  return Object.keys(section)
    .map((key) => {
      const name = normalizeVarName(key);
      const value = normalizeVarValue(section[key]);

      if (!name || value == null || value === '') {
        return null;
      }

      return `${name}: ${value};`;
    })
    .filter(Boolean);
}

function buildScssSource(themeConfig) {
  const normalizedTheme = normalizeThemeConfig(themeConfig);
  const globalVariables = collectVariables(normalizedTheme.global);
  const localVariables = collectVariables(normalizedTheme.local);

  return [
    '// Generated by server/theme-api.js',
    ...globalVariables,
    ...localVariables,
    '@import "index.scss";'
  ].join('\n');
}

function compileThemeCss(themeConfig) {
  if (!sass) {
    throw new Error('node-sass is not available. Please install dependencies before starting the theme API server.');
  }

  const result = sass.renderSync({
    data: buildScssSource(themeConfig),
    includePaths: [THEME_SRC_DIR],
    outputStyle: 'expanded'
  });

  return result.css.toString('utf8');
}

function extractDefaultTheme(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    const theme = {};
    const variablePattern = /^\s*(\$--[A-Za-z0-9_-]+):\s*(.+?)\s*!default;/gm;
    let match;

    while ((match = variablePattern.exec(content)) !== null) {
      theme[match[1]] = match[2].trim();
    }

    return theme;
  } catch (error) {
    return {};
  }
}

function getStoredTheme(version) {
  const key = version || 'default';
  if (!themeStore[key]) {
    themeStore[key] = {
      version: key,
      global: clone(defaultGlobalTheme),
      local: {},
      updatedAt: null,
      css: null
    };
  }

  return themeStore[key];
}

function saveTheme(version, themeConfig, css) {
  const key = version || 'default';
  const normalizedTheme = normalizeThemeConfig(themeConfig);

  themeStore[key] = {
    version: key,
    global: clone(normalizedTheme.global),
    local: clone(normalizedTheme.local),
    updatedAt: new Date().toISOString(),
    css
  };

  return themeStore[key];
}

function sendJson(res, statusCode, payload) {
  const body = JSON.stringify(payload, null, 2);

  res.writeHead(statusCode, {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Accept',
    'Content-Type': 'application/json; charset=utf-8',
    'Content-Length': Buffer.byteLength(body)
  });
  res.end(body);
}

function sendText(res, statusCode, body, contentType) {
  const text = typeof body === 'string' ? body : String(body || '');

  res.writeHead(statusCode, {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Accept',
    'Content-Type': contentType || 'text/plain; charset=utf-8',
    'Content-Length': Buffer.byteLength(text)
  });
  res.end(text);
}

function readRequestBody(req, callback) {
  let raw = '';

  req.on('data', (chunk) => {
    raw += chunk;
    if (raw.length > 1024 * 1024) {
      callback(new Error('Request body too large'));
      req.destroy();
    }
  });

  req.on('end', () => {
    if (!raw.trim()) {
      callback(null, null);
      return;
    }

    try {
      callback(null, JSON.parse(raw));
    } catch (error) {
      callback(new Error(`Invalid JSON body: ${error.message}`));
    }
  });

  req.on('error', callback);
}

function getVersionFromUrl(url) {
  return url.searchParams.get('version') || 'default';
}

function handleGetVariable(req, res, url) {
  const version = getVersionFromUrl(url);
  const stored = getStoredTheme(version);

  sendJson(res, 200, {
    version,
    global: stored.global,
    local: stored.local,
    updatedAt: stored.updatedAt,
    hasCss: Boolean(stored.css)
  });
}

function handleUpdateVariable(req, res, url) {
  const version = getVersionFromUrl(url);

  readRequestBody(req, (error, body) => {
    if (error) {
      sendJson(res, 400, {
        error: 'INVALID_REQUEST',
        message: error.message
      });
      return;
    }

    try {
      const themeConfig = normalizeThemeConfig(body);

      const css = compileThemeCss(themeConfig);

      saveTheme(version, themeConfig, css);
      sendText(res, 200, css, 'text/css; charset=utf-8');
    } catch (compileError) {
      sendJson(res, 500, {
        error: 'THEME_COMPILE_FAILED',
        message: compileError.message
      });
    }
  });
}

function handleHealth(req, res) {
  sendJson(res, 200, {
    ok: true,
    service: 'element-theme-api',
    port: PORT,
    themeSource: path.relative(ROOT_DIR, THEME_ENTRY_FILE),
    hasSass: Boolean(sass)
  });
}

const server = http.createServer((req, res) => {
  const requestUrl = new URL(req.url, `http://${req.headers.host || 'localhost'}`);
  const { pathname } = requestUrl;

  if (req.method === 'OPTIONS') {
    res.writeHead(204, {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Accept'
    });
    res.end();
    return;
  }

  if (req.method === 'GET' && pathname === '/') {
    handleHealth(req, res);
    return;
  }

  if (req.method === 'GET' && pathname === '/health') {
    handleHealth(req, res);
    return;
  }

  if (req.method === 'GET' && pathname === '/getVariable') {
    try {
      handleGetVariable(req, res, requestUrl);
    } catch (error) {
      sendJson(res, 500, {
        error: 'INTERNAL_SERVER_ERROR',
        message: error.message
      });
    }
    return;
  }

  if (req.method === 'POST' && pathname === '/updateVariable') {
    handleUpdateVariable(req, res, requestUrl);
    return;
  }

  sendJson(res, 404, {
    error: 'NOT_FOUND',
    message: `No route matches ${req.method} ${pathname}`
  });
});

server.listen(PORT, () => {
  // eslint-disable-next-line no-console
  console.log(`[theme-api] listening on http://localhost:${PORT}`);
  // eslint-disable-next-line no-console
  console.log(`[theme-api] SCSS entry: ${path.relative(ROOT_DIR, THEME_ENTRY_FILE)}`);
});
